name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing Deps
      run: npm i
    - name: Linting Project
      run: npm run lint
    - name: Running e2e
      run: npm run e2e
    - name: Runnind CI
      run: npm ci
    - name: Building
      run: npm run build
      env:
        CI: true